ALTER TABLE `gsprod`.`pledgebook_1` 
ADD COLUMN `IsRenewalBill` INT NULL DEFAULT 0 AFTER `Trashed`,
ADD COLUMN `IsRenewalOfBillNo` VARCHAR(45) NULL DEFAULT NULL AFTER `IsRenewalBill`,
ADD COLUMN `IsRenewalOfUID` VARCHAR(45) NULL DEFAULT NULL AFTER `IsRenewalOfBillNo`,
ADD COLUMN `Renewed` INT NULL DEFAULT 0 AFTER `IsRenewalOfUID`,
ADD COLUMN `RenewedNewBillNo` VARCHAR(45) NULL DEFAULT NULL AFTER `Renewed`,
ADD COLUMN `RenewedNewUID` VARCHAR(45) NULL DEFAULT NULL AFTER `RenewedNewBillNo`;
